[2025-02-18T04:29:06.784+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:29:06.817+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [queued]>
[2025-02-18T04:29:06.830+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [queued]>
[2025-02-18T04:29:06.830+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T04:29:07.106+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-12 17:58:00+00:00
[2025-02-18T04:29:07.126+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T04:29:07.129+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2025-02-18T04:29:07.131+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'scheduled__2025-02-12T17:58:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpiqi0v7i1']
[2025-02-18T04:29:07.132+0000] {standard_task_runner.py:105} INFO - Job 140: Subtask sensor_test
[2025-02-18T04:29:07.213+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [running]> on host d70a9c8071c1
[2025-02-18T04:29:07.355+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T17:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T17:58:00+00:00'
[2025-02-18T04:29:07.357+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T04:29:07.358+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T04:29:07.358+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-18 04:29:06.818082+00:00
[2025-02-18T04:29:07.358+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-18T04:29:07.359+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T04:29:07.359+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-18T04:29:07.378+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-18T04:29:07.395+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-18T04:29:07.396+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-18T04:29:09.322+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-18T04:29:09.653+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-18T04:29:09.654+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T04:29:09.722+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T04:29:09.760+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T04:29:09.762+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T04:29:41.451+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:29:41.470+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [queued]>
[2025-02-18T04:29:41.479+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [queued]>
[2025-02-18T04:29:41.480+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T04:29:41.495+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-12 17:58:00+00:00
[2025-02-18T04:29:41.509+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=114) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T04:29:41.510+0000] {standard_task_runner.py:72} INFO - Started process 118 to run task
[2025-02-18T04:29:41.511+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'scheduled__2025-02-12T17:58:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmp15v2fczl']
[2025-02-18T04:29:41.512+0000] {standard_task_runner.py:105} INFO - Job 148: Subtask sensor_test
[2025-02-18T04:29:41.772+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [running]> on host d70a9c8071c1
[2025-02-18T04:29:41.861+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T17:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T17:58:00+00:00'
[2025-02-18T04:29:41.862+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T04:29:41.863+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T04:29:41.863+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-18 04:29:41.471060+00:00
[2025-02-18T04:29:41.863+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-18T04:29:41.863+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T04:29:41.864+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-18T04:29:41.873+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-18T04:29:41.883+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-18T04:29:41.884+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-18T04:29:43.121+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-18T04:29:43.390+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-18T04:29:43.390+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T04:29:43.451+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T04:29:43.629+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T04:29:43.631+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T04:30:15.020+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:30:15.036+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [queued]>
[2025-02-18T04:30:15.043+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [queued]>
[2025-02-18T04:30:15.043+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T04:30:15.060+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-12 17:58:00+00:00
[2025-02-18T04:30:15.073+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T04:30:15.075+0000] {standard_task_runner.py:72} INFO - Started process 133 to run task
[2025-02-18T04:30:15.075+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'scheduled__2025-02-12T17:58:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpj1xjpj68']
[2025-02-18T04:30:15.076+0000] {standard_task_runner.py:105} INFO - Job 150: Subtask sensor_test
[2025-02-18T04:30:15.326+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [running]> on host d70a9c8071c1
[2025-02-18T04:30:15.415+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T17:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T17:58:00+00:00'
[2025-02-18T04:30:15.415+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T04:30:15.416+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T04:30:15.416+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-18 04:30:15.036574+00:00
[2025-02-18T04:30:15.416+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-18T04:30:15.416+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T04:30:15.416+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-18T04:30:15.425+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-18T04:30:15.437+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-18T04:30:15.438+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-18T04:30:16.605+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-18T04:30:16.857+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-18T04:30:16.858+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T04:30:16.895+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T04:30:17.071+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T04:30:17.075+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T04:30:49.376+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:30:49.392+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [queued]>
[2025-02-18T04:30:49.400+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [queued]>
[2025-02-18T04:30:49.400+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T04:30:49.413+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-12 17:58:00+00:00
[2025-02-18T04:30:49.425+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=144) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T04:30:49.426+0000] {standard_task_runner.py:72} INFO - Started process 149 to run task
[2025-02-18T04:30:49.427+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'scheduled__2025-02-12T17:58:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpxozp0yjg']
[2025-02-18T04:30:49.428+0000] {standard_task_runner.py:105} INFO - Job 153: Subtask sensor_test
[2025-02-18T04:30:49.672+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [running]> on host d70a9c8071c1
[2025-02-18T04:30:49.758+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T17:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T17:58:00+00:00'
[2025-02-18T04:30:49.758+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T04:30:49.759+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T04:30:49.759+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-18 04:30:49.392881+00:00
[2025-02-18T04:30:49.759+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-18T04:30:49.759+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T04:30:49.760+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-18T04:30:49.769+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-18T04:30:49.778+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-18T04:30:49.779+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-18T04:30:51.004+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-18T04:30:51.252+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-18T04:30:51.253+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T04:30:51.286+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T04:30:51.467+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T04:30:51.477+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T04:31:23.890+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:31:23.907+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [queued]>
[2025-02-18T04:31:23.915+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [queued]>
[2025-02-18T04:31:23.916+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T04:31:23.929+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-12 17:58:00+00:00
[2025-02-18T04:31:23.941+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=160) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T04:31:23.943+0000] {standard_task_runner.py:72} INFO - Started process 165 to run task
[2025-02-18T04:31:23.943+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'scheduled__2025-02-12T17:58:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmp550ozer5']
[2025-02-18T04:31:23.944+0000] {standard_task_runner.py:105} INFO - Job 155: Subtask sensor_test
[2025-02-18T04:31:24.203+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-12T17:58:00+00:00 [running]> on host d70a9c8071c1
[2025-02-18T04:31:24.296+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T17:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T17:58:00+00:00'
[2025-02-18T04:31:24.296+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T04:31:24.297+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T04:31:24.297+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-18 04:31:23.907960+00:00
[2025-02-18T04:31:24.297+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-18T04:31:24.297+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T04:31:24.298+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-18T04:31:24.307+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-18T04:31:24.319+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-18T04:31:24.320+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-18T04:31:30.609+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-18T04:31:30.908+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 187, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 143.641759 seconds exceeds the specified timeout of 120.0.
[2025-02-18T04:31:30.918+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-18T04:31:30.918+0000] {logging_mixin.py:190} INFO - Task start:2025-02-18 04:31:23.907960+00:00 end:2025-02-18 04:31:30.918061+00:00 duration:7.010101
[2025-02-18T04:31:30.919+0000] {logging_mixin.py:190} INFO - Task:<Task(S3KeySensor): sensor_test> dag:<DAG: sensor_timeout> dagrun:<DagRun sensor_timeout @ 2025-02-12 17:58:00+00:00: scheduled__2025-02-12T17:58:00+00:00, state:running, queued_at: 2025-02-18 04:28:59.552982+00:00. externally triggered: False>
[2025-02-18T04:31:30.919+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 143.641759 seconds exceeds the specified timeout of 120.0.
[2025-02-18T04:31:30.919+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=sensor_timeout, task_id=sensor_test, run_id=scheduled__2025-02-12T17:58:00+00:00, execution_date=20250212T175800, start_date=20250218T043123, end_date=20250218T043130
[2025-02-18T04:31:30.932+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T04:31:30.932+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 155 for task sensor_test (Sensor has timed out; run duration of 143.641759 seconds exceeds the specified timeout of 120.0.; 165)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 187, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 143.641759 seconds exceeds the specified timeout of 120.0.
[2025-02-18T04:31:30.978+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-18T04:31:30.994+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T04:31:30.995+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
