[2025-02-13T04:30:00.866+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T04:30:00.882+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [queued]>
[2025-02-13T04:30:00.891+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [queued]>
[2025-02-13T04:30:00.892+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-13T04:30:00.905+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-13 04:29:58.637913+00:00
[2025-02-13T04:30:00.918+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=274) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T04:30:00.919+0000] {standard_task_runner.py:72} INFO - Started process 276 to run task
[2025-02-13T04:30:00.920+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'manual__2025-02-13T04:29:58.637913+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpziwp9t0k']
[2025-02-13T04:30:00.921+0000] {standard_task_runner.py:105} INFO - Job 133: Subtask sensor_test
[2025-02-13T04:30:01.182+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [running]> on host 182dcabfe56a
[2025-02-13T04:30:01.285+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T04:29:58.637913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T04:29:58.637913+00:00'
[2025-02-13T04:30:01.286+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-13T04:30:01.286+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-13T04:30:01.286+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-13 04:30:00.883065+00:00
[2025-02-13T04:30:01.286+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-13T04:30:01.287+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-13T04:30:01.287+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-13T04:30:01.298+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-13T04:30:01.311+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-13T04:30:01.312+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-13T04:30:02.490+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-13T04:30:02.731+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-13T04:30:02.731+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-13T04:30:02.778+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T04:30:03.021+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T04:30:03.023+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-13T04:30:34.299+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T04:30:34.315+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [queued]>
[2025-02-13T04:30:34.324+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [queued]>
[2025-02-13T04:30:34.324+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-13T04:30:34.339+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-13 04:29:58.637913+00:00
[2025-02-13T04:30:34.351+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=285) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T04:30:34.354+0000] {standard_task_runner.py:72} INFO - Started process 287 to run task
[2025-02-13T04:30:34.354+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'manual__2025-02-13T04:29:58.637913+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmp7ju37we1']
[2025-02-13T04:30:34.355+0000] {standard_task_runner.py:105} INFO - Job 134: Subtask sensor_test
[2025-02-13T04:30:34.653+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [running]> on host 182dcabfe56a
[2025-02-13T04:30:34.748+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T04:29:58.637913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T04:29:58.637913+00:00'
[2025-02-13T04:30:34.749+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-13T04:30:34.749+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-13T04:30:34.749+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-13 04:30:34.316030+00:00
[2025-02-13T04:30:34.749+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-13T04:30:34.749+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-13T04:30:34.749+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-13T04:30:34.760+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-13T04:30:34.772+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-13T04:30:34.772+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-13T04:30:36.064+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-13T04:30:36.315+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-13T04:30:36.316+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-13T04:30:36.372+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T04:30:36.615+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T04:30:36.617+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-13T04:31:08.847+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T04:31:08.865+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [queued]>
[2025-02-13T04:31:08.874+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [queued]>
[2025-02-13T04:31:08.874+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-13T04:31:08.888+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-13 04:29:58.637913+00:00
[2025-02-13T04:31:08.899+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=296) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T04:31:08.900+0000] {standard_task_runner.py:72} INFO - Started process 298 to run task
[2025-02-13T04:31:08.901+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'manual__2025-02-13T04:29:58.637913+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpcsogc6pn']
[2025-02-13T04:31:08.902+0000] {standard_task_runner.py:105} INFO - Job 135: Subtask sensor_test
[2025-02-13T04:31:09.140+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [running]> on host 182dcabfe56a
[2025-02-13T04:31:09.223+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T04:29:58.637913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T04:29:58.637913+00:00'
[2025-02-13T04:31:09.223+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-13T04:31:09.224+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-13T04:31:09.224+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-13 04:31:08.866009+00:00
[2025-02-13T04:31:09.224+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-13T04:31:09.224+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-13T04:31:09.224+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-13T04:31:09.234+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-13T04:31:09.245+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-13T04:31:09.246+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-13T04:31:10.471+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-13T04:31:10.709+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-13T04:31:10.710+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-13T04:31:10.759+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T04:31:10.957+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T04:31:10.958+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-13T04:31:42.492+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T04:31:42.509+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [queued]>
[2025-02-13T04:31:42.516+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [queued]>
[2025-02-13T04:31:42.517+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-13T04:31:42.530+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-13 04:29:58.637913+00:00
[2025-02-13T04:31:42.541+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=307) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T04:31:42.542+0000] {standard_task_runner.py:72} INFO - Started process 309 to run task
[2025-02-13T04:31:42.543+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'manual__2025-02-13T04:29:58.637913+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpm3w61tec']
[2025-02-13T04:31:42.544+0000] {standard_task_runner.py:105} INFO - Job 136: Subtask sensor_test
[2025-02-13T04:31:42.789+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [running]> on host 182dcabfe56a
[2025-02-13T04:31:42.866+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T04:29:58.637913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T04:29:58.637913+00:00'
[2025-02-13T04:31:42.867+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-13T04:31:42.867+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-13T04:31:42.868+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-13 04:31:42.510011+00:00
[2025-02-13T04:31:42.868+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-13T04:31:42.868+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-13T04:31:42.868+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-13T04:31:42.878+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-13T04:31:42.889+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-13T04:31:42.890+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-13T04:31:46.072+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-13T04:31:46.329+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-13T04:31:46.329+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-13T04:31:46.367+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T04:31:46.605+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T04:31:46.607+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-13T04:32:18.386+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T04:32:18.408+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [queued]>
[2025-02-13T04:32:18.419+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [queued]>
[2025-02-13T04:32:18.420+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-13T04:32:18.438+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-13 04:29:58.637913+00:00
[2025-02-13T04:32:18.454+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=318) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T04:32:18.456+0000] {standard_task_runner.py:72} INFO - Started process 320 to run task
[2025-02-13T04:32:18.457+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'manual__2025-02-13T04:29:58.637913+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpeljdcycc']
[2025-02-13T04:32:18.458+0000] {standard_task_runner.py:105} INFO - Job 137: Subtask sensor_test
[2025-02-13T04:32:18.810+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test manual__2025-02-13T04:29:58.637913+00:00 [running]> on host 182dcabfe56a
[2025-02-13T04:32:18.903+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T04:29:58.637913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T04:29:58.637913+00:00'
[2025-02-13T04:32:18.903+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-13T04:32:18.904+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-13T04:32:18.904+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-13 04:32:18.409058+00:00
[2025-02-13T04:32:18.904+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-13T04:32:18.904+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-13T04:32:18.905+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-13T04:32:18.916+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-13T04:32:18.929+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-13T04:32:18.929+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-13T04:32:20.132+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-13T04:32:20.358+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 187, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 139.1411 seconds exceeds the specified timeout of 120.0.
[2025-02-13T04:32:20.368+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-13T04:32:20.368+0000] {logging_mixin.py:190} INFO - Task start:2025-02-13 04:32:18.409058+00:00 end:2025-02-13 04:32:20.367922+00:00 duration:1.958864
[2025-02-13T04:32:20.368+0000] {logging_mixin.py:190} INFO - Task:<Task(S3KeySensor): sensor_test> dag:<DAG: sensor_timeout> dagrun:<DagRun sensor_timeout @ 2025-02-13 04:29:58.637913+00:00: manual__2025-02-13T04:29:58.637913+00:00, state:running, queued_at: 2025-02-13 04:29:58.653047+00:00. externally triggered: True>
[2025-02-13T04:32:20.368+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 139.1411 seconds exceeds the specified timeout of 120.0.
[2025-02-13T04:32:20.369+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=sensor_timeout, task_id=sensor_test, run_id=manual__2025-02-13T04:29:58.637913+00:00, execution_date=20250213T042958, start_date=20250213T043218, end_date=20250213T043220
[2025-02-13T04:32:20.389+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-13T04:32:20.389+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 137 for task sensor_test (Sensor has timed out; run duration of 139.1411 seconds exceeds the specified timeout of 120.0.; 320)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 187, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 139.1411 seconds exceeds the specified timeout of 120.0.
[2025-02-13T04:32:20.436+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-13T04:32:20.615+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T04:32:20.617+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
