[2025-02-12T05:14:13.084+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T05:14:13.109+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-12T05:14:10.140347+00:00 [queued]>
[2025-02-12T05:14:13.122+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-12T05:14:10.140347+00:00 [queued]>
[2025-02-12T05:14:13.122+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T05:14:13.145+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-12 05:14:10.140347+00:00
[2025-02-12T05:14:13.165+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=219) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T05:14:13.168+0000] {standard_task_runner.py:72} INFO - Started process 221 to run task
[2025-02-12T05:14:13.169+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'manual__2025-02-12T05:14:10.140347+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmp303sm1v1']
[2025-02-12T05:14:13.170+0000] {standard_task_runner.py:105} INFO - Job 118: Subtask sensor_test
[2025-02-12T05:14:13.511+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test manual__2025-02-12T05:14:10.140347+00:00 [running]> on host 3b1fc8480f51
[2025-02-12T05:14:13.681+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T05:14:10.140347+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T05:14:10.140347+00:00'
[2025-02-12T05:14:13.682+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-12T05:14:13.682+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-12T05:14:13.683+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-12 05:14:13.109809+00:00
[2025-02-12T05:14:13.683+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-12T05:14:13.684+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T05:14:13.684+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-12T05:14:13.685+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:14:13.701+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-12T05:14:13.702+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-12T05:14:18.659+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:14:22.911+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:14:22.913+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:14:27.104+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:14:27.106+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:14:31.300+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:14:31.303+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:14:35.498+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:14:35.501+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:14:39.693+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:14:39.694+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:14:43.888+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:14:43.891+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:14:48.083+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:14:48.085+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:14:52.276+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:14:52.278+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:14:56.470+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:14:56.473+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:14:56.668+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 187, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 42.98277832799977 seconds exceeds the specified timeout of 40.0.
[2025-02-12T05:14:56.680+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-12T05:14:56.680+0000] {logging_mixin.py:190} INFO - Task start:2025-02-12 05:14:13.109809+00:00 end:2025-02-12 05:14:56.680088+00:00 duration:43.570279
[2025-02-12T05:14:56.681+0000] {logging_mixin.py:190} INFO - Task:<Task(S3KeySensor): sensor_test> dag:<DAG: sensor_timeout> dagrun:<DagRun sensor_timeout @ 2025-02-12 05:14:10.140347+00:00: manual__2025-02-12T05:14:10.140347+00:00, state:running, queued_at: 2025-02-12 05:14:10.159484+00:00. externally triggered: True>
[2025-02-12T05:14:56.681+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 42.98277832799977 seconds exceeds the specified timeout of 40.0.
[2025-02-12T05:14:56.681+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=sensor_timeout, task_id=sensor_test, run_id=manual__2025-02-12T05:14:10.140347+00:00, execution_date=20250212T051410, start_date=20250212T051413, end_date=20250212T051456
[2025-02-12T05:14:56.708+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T05:14:56.708+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 118 for task sensor_test (Sensor has timed out; run duration of 42.98277832799977 seconds exceeds the specified timeout of 40.0.; 221)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 187, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 42.98277832799977 seconds exceeds the specified timeout of 40.0.
[2025-02-12T05:14:56.786+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-12T05:14:56.811+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T05:14:56.813+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
