[2025-02-12T05:20:42.638+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T05:20:42.665+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-12T05:20:40.164486+00:00 [queued]>
[2025-02-12T05:20:42.679+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-12T05:20:40.164486+00:00 [queued]>
[2025-02-12T05:20:42.679+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T05:20:42.704+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-12 05:20:40.164486+00:00
[2025-02-12T05:20:42.721+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=327) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T05:20:42.723+0000] {standard_task_runner.py:72} INFO - Started process 329 to run task
[2025-02-12T05:20:42.724+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'manual__2025-02-12T05:20:40.164486+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpzbzh3hqg']
[2025-02-12T05:20:42.725+0000] {standard_task_runner.py:105} INFO - Job 124: Subtask sensor_test
[2025-02-12T05:20:43.077+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test manual__2025-02-12T05:20:40.164486+00:00 [running]> on host 3b1fc8480f51
[2025-02-12T05:20:43.192+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T05:20:40.164486+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T05:20:40.164486+00:00'
[2025-02-12T05:20:43.193+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-12T05:20:43.193+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-12T05:20:43.194+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-12 05:20:42.665618+00:00
[2025-02-12T05:20:43.194+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-12T05:20:43.194+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T05:20:43.195+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-12T05:20:43.208+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-12T05:20:43.208+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-12T05:20:57.689+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-12T05:20:57.897+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-02-12T05:20:57.916+0000] {taskinstance.py:288} INFO - Pausing task as DEFERRED. dag_id=sensor_timeout, task_id=sensor_test, run_id=manual__2025-02-12T05:20:40.164486+00:00, execution_date=20250212T052040, start_date=20250212T052042
[2025-02-12T05:20:57.916+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T05:20:57.969+0000] {local_task_job_runner.py:260} INFO - Task exited with return code 100 (task deferral)
[2025-02-12T05:20:57.969+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-12T05:23:13.025+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T05:23:13.042+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-12T05:20:40.164486+00:00 [queued]>
[2025-02-12T05:23:13.050+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test manual__2025-02-12T05:20:40.164486+00:00 [queued]>
[2025-02-12T05:23:13.050+0000] {taskinstance.py:2864} INFO - Resuming after deferral
[2025-02-12T05:23:13.064+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-12 05:20:40.164486+00:00
[2025-02-12T05:23:13.075+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=359) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T05:23:13.076+0000] {standard_task_runner.py:72} INFO - Started process 361 to run task
[2025-02-12T05:23:13.077+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'manual__2025-02-12T05:20:40.164486+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmprktcr85g']
[2025-02-12T05:23:13.078+0000] {standard_task_runner.py:105} INFO - Job 125: Subtask sensor_test
[2025-02-12T05:23:13.327+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test manual__2025-02-12T05:20:40.164486+00:00 [running]> on host 3b1fc8480f51
[2025-02-12T05:23:13.398+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-12T05:23:13.399+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-12T05:23:13.399+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-12 05:20:42.665618+00:00
[2025-02-12T05:23:13.399+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-12T05:23:13.399+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T05:23:13.410+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 341, in resume_execution
    return super().resume_execution(next_method, next_kwargs, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1807, in resume_execution
    raise TaskDeferralError(next_kwargs.get("error", "Unknown"))
airflow.exceptions.TaskDeferralError: Trigger/execution timeout
[2025-02-12T05:23:13.414+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-12T05:23:13.414+0000] {logging_mixin.py:190} INFO - Task start:2025-02-12 05:20:42.665618+00:00 end:2025-02-12 05:23:13.413890+00:00 duration:150.748272
[2025-02-12T05:23:13.414+0000] {logging_mixin.py:190} INFO - Task:<Task(S3KeySensor): sensor_test> dag:<DAG: sensor_timeout> dagrun:<DagRun sensor_timeout @ 2025-02-12 05:20:40.164486+00:00: manual__2025-02-12T05:20:40.164486+00:00, state:running, queued_at: 2025-02-12 05:20:40.177413+00:00. externally triggered: True>
[2025-02-12T05:23:13.415+0000] {logging_mixin.py:190} INFO - Failure caused by Trigger/execution timeout
[2025-02-12T05:23:13.415+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=sensor_timeout, task_id=sensor_test, run_id=manual__2025-02-12T05:20:40.164486+00:00, execution_date=20250212T052040, start_date=20250212T052042, end_date=20250212T052313
[2025-02-12T05:23:13.428+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T05:23:13.428+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 125 for task sensor_test (Trigger/execution timeout; 361)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 341, in resume_execution
    return super().resume_execution(next_method, next_kwargs, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1807, in resume_execution
    raise TaskDeferralError(next_kwargs.get("error", "Unknown"))
airflow.exceptions.TaskDeferralError: Trigger/execution timeout
[2025-02-12T05:23:13.451+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-12T05:23:13.618+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T05:23:13.620+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
