[2025-02-18T04:29:06.792+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:29:06.822+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [queued]>
[2025-02-18T04:29:06.837+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [queued]>
[2025-02-18T04:29:06.837+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T04:29:07.099+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-16 17:58:00+00:00
[2025-02-18T04:29:07.118+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=74) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T04:29:07.120+0000] {standard_task_runner.py:72} INFO - Started process 82 to run task
[2025-02-18T04:29:07.121+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'scheduled__2025-02-16T17:58:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpq64b5qe3']
[2025-02-18T04:29:07.123+0000] {standard_task_runner.py:105} INFO - Job 143: Subtask sensor_test
[2025-02-18T04:29:07.206+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [running]> on host d70a9c8071c1
[2025-02-18T04:29:07.363+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T17:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-16T17:58:00+00:00'
[2025-02-18T04:29:07.365+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T04:29:07.366+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T04:29:07.366+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-18 04:29:06.823541+00:00
[2025-02-18T04:29:07.367+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-18T04:29:07.367+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T04:29:07.368+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-18T04:29:07.384+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-18T04:29:07.401+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-18T04:29:07.402+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-18T04:29:09.346+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-18T04:29:09.652+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-18T04:29:09.653+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T04:29:09.708+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T04:29:09.744+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T04:29:09.747+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T04:29:41.463+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:29:41.483+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [queued]>
[2025-02-18T04:29:41.491+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [queued]>
[2025-02-18T04:29:41.492+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T04:29:41.506+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-16 17:58:00+00:00
[2025-02-18T04:29:41.520+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=115) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T04:29:41.522+0000] {standard_task_runner.py:72} INFO - Started process 120 to run task
[2025-02-18T04:29:41.522+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'scheduled__2025-02-16T17:58:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmptojhxlrq']
[2025-02-18T04:29:41.523+0000] {standard_task_runner.py:105} INFO - Job 149: Subtask sensor_test
[2025-02-18T04:29:41.778+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [running]> on host d70a9c8071c1
[2025-02-18T04:29:41.868+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T17:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-16T17:58:00+00:00'
[2025-02-18T04:29:41.869+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T04:29:41.869+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T04:29:41.869+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-18 04:29:41.483646+00:00
[2025-02-18T04:29:41.869+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-18T04:29:41.870+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T04:29:41.870+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-18T04:29:41.879+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-18T04:29:41.889+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-18T04:29:41.890+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-18T04:29:43.122+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-18T04:29:43.388+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-18T04:29:43.389+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T04:29:43.422+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T04:29:43.602+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T04:29:43.604+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T04:30:15.022+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:30:15.040+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [queued]>
[2025-02-18T04:30:15.048+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [queued]>
[2025-02-18T04:30:15.049+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T04:30:15.065+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-16 17:58:00+00:00
[2025-02-18T04:30:15.079+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T04:30:15.080+0000] {standard_task_runner.py:72} INFO - Started process 135 to run task
[2025-02-18T04:30:15.081+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'scheduled__2025-02-16T17:58:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpe_m83cvu']
[2025-02-18T04:30:15.082+0000] {standard_task_runner.py:105} INFO - Job 151: Subtask sensor_test
[2025-02-18T04:30:15.329+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [running]> on host d70a9c8071c1
[2025-02-18T04:30:15.415+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T17:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-16T17:58:00+00:00'
[2025-02-18T04:30:15.416+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T04:30:15.416+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T04:30:15.417+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-18 04:30:15.041154+00:00
[2025-02-18T04:30:15.417+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-18T04:30:15.417+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T04:30:15.417+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-18T04:30:15.425+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-18T04:30:15.437+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-18T04:30:15.438+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-18T04:30:16.601+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-18T04:30:16.856+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-18T04:30:16.857+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T04:30:16.901+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T04:30:17.076+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T04:30:17.078+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T04:30:49.375+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:30:49.391+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [queued]>
[2025-02-18T04:30:49.399+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [queued]>
[2025-02-18T04:30:49.400+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T04:30:49.414+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-16 17:58:00+00:00
[2025-02-18T04:30:49.425+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T04:30:49.426+0000] {standard_task_runner.py:72} INFO - Started process 148 to run task
[2025-02-18T04:30:49.427+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'scheduled__2025-02-16T17:58:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpidrer6k2']
[2025-02-18T04:30:49.428+0000] {standard_task_runner.py:105} INFO - Job 152: Subtask sensor_test
[2025-02-18T04:30:49.673+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [running]> on host d70a9c8071c1
[2025-02-18T04:30:49.756+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T17:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-16T17:58:00+00:00'
[2025-02-18T04:30:49.757+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T04:30:49.757+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T04:30:49.757+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-18 04:30:49.392134+00:00
[2025-02-18T04:30:49.757+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-18T04:30:49.758+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T04:30:49.758+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-18T04:30:49.768+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-18T04:30:49.779+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-18T04:30:49.779+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-18T04:30:51.020+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-18T04:30:51.271+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-18T04:30:51.272+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T04:30:51.326+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T04:30:51.503+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T04:30:51.504+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T04:31:23.857+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:31:23.875+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [queued]>
[2025-02-18T04:31:23.882+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [queued]>
[2025-02-18T04:31:23.883+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T04:31:23.895+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_test> on 2025-02-16 17:58:00+00:00
[2025-02-18T04:31:23.906+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=159) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T04:31:23.908+0000] {standard_task_runner.py:72} INFO - Started process 163 to run task
[2025-02-18T04:31:23.908+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sensor_timeout', 'sensor_test', 'scheduled__2025-02-16T17:58:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/s3test_dag.py', '--cfg-path', '/tmp/tmpsbwf6vv4']
[2025-02-18T04:31:23.909+0000] {standard_task_runner.py:105} INFO - Job 154: Subtask sensor_test
[2025-02-18T04:31:24.172+0000] {task_command.py:467} INFO - Running <TaskInstance: sensor_timeout.sensor_test scheduled__2025-02-16T17:58:00+00:00 [running]> on host d70a9c8071c1
[2025-02-18T04:31:24.263+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_timeout' AIRFLOW_CTX_TASK_ID='sensor_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T17:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-16T17:58:00+00:00'
[2025-02-18T04:31:24.264+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T04:31:24.264+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T04:31:24.265+0000] {logging_mixin.py:190} INFO - Current task name:sensor_test state:running start_date:2025-02-18 04:31:23.875357+00:00
[2025-02-18T04:31:24.265+0000] {logging_mixin.py:190} INFO - Dag name:sensor_timeout and current dag run status:running
[2025-02-18T04:31:24.265+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T04:31:24.265+0000] {baseoperator.py:421} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-02-18T04:31:24.275+0000] {s3.py:116} INFO - Poking for key : s3://***-test-benhur/data.csv
[2025-02-18T04:31:24.288+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-18T04:31:24.289+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-02-18T04:31:30.575+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '***-test-benhur.s3.eu-north-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[2025-02-18T04:31:30.857+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 187, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 143.594912 seconds exceeds the specified timeout of 120.0.
[2025-02-18T04:31:30.868+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-18T04:31:30.868+0000] {logging_mixin.py:190} INFO - Task start:2025-02-18 04:31:23.875357+00:00 end:2025-02-18 04:31:30.867929+00:00 duration:6.992572
[2025-02-18T04:31:30.869+0000] {logging_mixin.py:190} INFO - Task:<Task(S3KeySensor): sensor_test> dag:<DAG: sensor_timeout> dagrun:<DagRun sensor_timeout @ 2025-02-16 17:58:00+00:00: scheduled__2025-02-16T17:58:00+00:00, state:running, queued_at: 2025-02-18 04:29:00.199708+00:00. externally triggered: False>
[2025-02-18T04:31:30.869+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 143.594912 seconds exceeds the specified timeout of 120.0.
[2025-02-18T04:31:30.869+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=sensor_timeout, task_id=sensor_test, run_id=scheduled__2025-02-16T17:58:00+00:00, execution_date=20250216T175800, start_date=20250218T043123, end_date=20250218T043130
[2025-02-18T04:31:30.884+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T04:31:30.884+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 154 for task sensor_test (Sensor has timed out; run duration of 143.594912 seconds exceeds the specified timeout of 120.0.; 163)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 187, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 143.594912 seconds exceeds the specified timeout of 120.0.
[2025-02-18T04:31:30.942+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-18T04:31:30.959+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T04:31:30.960+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
